apiVersion: v1
kind: Service
metadata:
  name: clients-nodeport-srv
spec:
  type: NodePort
  selector:
    app: clients
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30005
      name: client-service
 
    